### ISSUE TITLE
Develop integration tests for drag and drop

### ISSUE THREAD

**Issue by arecvlohe** [citrusbyte/react-big-calendar#63]
## Description

Develop integration tests for drag and drop functionality within the calendar.

### Items to Test

- [ ] Move event onto another day
- [ ] Move event onto another day and reorder
- [ ] Reorder event in day
- [ ] Resize event from left
- [ ] Resize event from right

## Estimation

3 - 5 Days

**Comment by abelino** [comment]
perfect, I think 3-5 days is accurate at this point.
